Add files via upload
bhylak/the-rat pull request #1
Opened 2019-02-08 22:10 UTC by marzpuente

support files for flask camera server

2019-02-09 20:36 UTC, bhylak commented
Can you add a screenshot of your work, any current limitations, etc.

2019-02-10 19:59 UTC, bhylak commented
@marzpuente bump

2019-02-11 00:24 UTC, marzpuente commented
@benhylak here are some screenshots. Picamera works great. I just need to run Mona's thermal code to pipe the images to the program that reading the images and animates them on the page.
![sprintfeb102](https://user-images.githubusercontent.com/25962690/52542006-87858000-2d69-11e9-986c-87b9384ae754.PNG)
![sprintfeb10](https://user-images.githubusercontent.com/25962690/52542007-87858000-2d69-11e9-9faf-9c16c285d6c8.PNG)

2019-02-11 02:36 UTC, benhylak reviewed
remove extra image files (1, 2, 3.jpg)

2019-02-11 02:46 UTC, benhylak requested changes
To be honest, I'm super confused.

You have a camera.py file, a base_camera.py file, base_thermal_camera.py file, a camera_pi.py, among others. The base_camera_thermal.py. 

The camera.py file, which has the ThermalCamera class, is just reading in images instead of actually reading in from the thermal camera (which is what we need...)

base_camera_thermal and base_camera seem to be the exact same thing, more or less. Not sure what the difference is.

.pyc files should not be committed to the repo. They're just artifacts of the build process.

Classes and files should be labeled or self explanatory. 

Also, please be clearer about what does and does not work. The thermal camera class appears to work but is just looping through 4 images. That can lead to a ton of confusion down the line.

2019-02-11 02:46 UTC, bhylak commented on SW/Python/flask-video-streaming-master/app.py
> +    from camera import CameraThermal
rename to ThermalCamera

2019-02-11 02:46 UTC, bhylak commented on SW/Python/flask-video-streaming-master/base_camera.py.txt
> +class BaseCamera(object):
delete this file? (it's a .txt?)

2019-02-25 00:23 UTC, closed without merging